# Generated by Django 4.1.3 on 2022-11-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_code', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('receipt_type', models.CharField(blank=True, choices=[('GrabFood', 'GrabFood'), ('Foodpanda', 'Foodpanda')], max_length=150)),
                ('delivery_date', models.CharField(max_length=150)),
                ('receipt_total_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_assigned', models.BooleanField(default=False)),
                ('assignment', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.item')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.receipt')),
            ],
        ),
    ]
