# Generated by Django 4.1.3 on 2022-11-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='assignment',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
